version: "3.8"

services:
  help_desk:
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    command: mix phx.server
    restart: unless-stopped
    ports:
      - "4001:4000"
    expose:
      - "4001"

    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
      - help_desk_build:/app/_build/
      - help_desk_deps:/app/deps
    env_file:
      - .env
    networks:
      - help_desk_network

  db:
    container_name: help_desk_db
    restart: always
    image: postgres:13.5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: help_desk_dev
    ports:
      - "5434:5432"
    volumes:
      - help_desk:/var/lib/postgresql/data/
      - ./dump:/home/
    networks:
      - help_desk_network

networks:
  help_desk_network:
    name: help_desk_network

volumes:
  help_desk_build:
  help_desk_deps:
  help_desk:
