version: "3.8"

services:
  core:
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    command: mix phx.server
    restart: unless-stopped
    ports:
      - "4000:4000"
    expose:
      - "4000"

    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
      - core_build:/app/_build/
      - core_deps:/app/deps
    env_file:
      - .env
    networks:
      - core_network

  db:
    container_name: core_db
    restart: always
    image: postgres:13.5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: core_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_core:/var/lib/postgresql/data/
      - ./dump:/home/
    networks:
      - core_network

networks:
  core_network:
    name: core_network

volumes:
  core_build:
  core_deps:
  postgres_core:
